version: '3'
services:
  bot:
    env_file: .env
    image: node:14-alpine
    container_name: gif-tagger-bot
    working_dir: /app
    volumes: 
      - .:/app
    entrypoint: npm run watch
  mongo_db:
    image: mongo
    env_file: .env
    container_name: gif-tagger-db
    volumes: 
      - ./data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports: 
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: gif_tagger_db
    # command: mongod --quiet --logpath /dev/null 
networks:
  bot_network:
    driver: bridge
